name: Update Resume Gist

on: 
  push:
    branches: [main]
    paths:
      - 'en/resume.json'
      - '.github/workflows/gist.yml'
      - 'package.json'
      - 'package-lock.json'
  workflow_dispatch:

jobs:
  update-English-resume-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Update Resume Gist
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.TOKEN }}
          gist_id: 46d5f3465f6ad966d0226a447647152d
          file_path: en/resume.json
